### ISSUE TITLE
Implement Abstract Syntax Tree (AST)

### ISSUE THREAD

**Issue by tamercuba** [tamercuba/risp#8]
## Description
We need to implement an Abstract Syntax Tree (AST) for our Lisp interpreter. This will help in better organizing the structure of our code and making it more extensible for future features. The AST will serve as an intermediate representation of the code, allowing us to separate parsing and evaluation phases and enabling more sophisticated optimizations and analysis.

## Motivation
Currently, our interpreter directly parses and evaluates expressions. This approach is simple but lacks flexibility and scalability. By introducing an AST, we can:

- **Improve Readability and Maintainability**: An AST will make the structure of our code more transparent and easier to understand.
- **Enable Advanced Features**: Features like macro systems, optimizations, and more sophisticated error reporting will become easier to implement.
- **Separate Concerns**: Decoupling parsing from evaluation allows for cleaner and more modular code.

## Implementation Plan

1. **Define AST Nodes**: 
    - Create a set of structs/enums to represent different types of expressions (e.g., literals, variables, function calls, etc.).
    - Each node should implement traits for debugging and potentially other traits (e.g., Clone, PartialEq) as needed.

2. **Modify the Parser**:
    - Update the parser to build the AST.
    - Ensure that the parser handles all current expressions and edge cases correctly.

3. **Update the Evaluator**:
    - Implement an evaluator that traverses the AST and evaluates the expressions.
    - Ensure the evaluator handles all current operations and integrates seamlessly with existing functionality.

4. **Testing and Validation**:
    - Write comprehensive tests for both the parser and evaluator.
    - Ensure that all existing tests pass and cover new edge cases introduced by the AST.

5. **Documentation**:
    - Update the project documentation to include information about the AST.
    - Provide examples and guides on how to work with the new AST structure.

#### Example
Here is a high-level example of what the AST might look like:

```rust
enum ASTNode {
    Integer(i64),
    Bool(bool),
    Symbol(String),
    List(Vec<ASTNode>),
    FunctionCall {
        name: Box<ASTNode>,
        args: Vec<ASTNode>,
    },
    // Additional nodes as needed
}

// Example usage in parser:
fn parse(tokens: &[Token]) -> Result<ASTNode, ParseError> {
    // Parsing logic to build AST
}

// Example usage in evaluator:
fn evaluate(&mut self, node: &ASTNode) -> Result<Object, EvalError> {
    // Evaluation logic
}
```

## References

- [Crafting Interpreters](http://craftinginterpreters.com/) *...current reading...* 
- [Lisp in Small Pieces](https://books.google.com.br/books/about/Lisp_in_Small_Pieces.html?id=iCrrcMA6TYwC&redir_esc=y) **TODO** 

By implementing an AST, we will lay a strong foundation for future enhancements and maintain a clean, modular codebase.

## Tasks

- [ ] Define AST Node structs/enums
- [ ] Update the parser to generate AST
- [ ] Implement the evaluator for AST
- [ ] Write and update tests for the parser and evaluator
- [ ] Update project documentation
